<?php
/**
 * ページテンプレート向けローカル ACF フィールドグループ。
 *
 * @package Theme
 */

declare(strict_types=1);

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Register ACF groups for page templates.
 */
function theme_register_acf_page_template_groups(): void {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	$td = THEME_GETTEXT_DOMAIN;

	$tpl_loc = static function ( string $relative_template ): array {
		return array(
			array(
				array(
					'param'    => 'page_template',
					'operator' => '==',
					'value'    => $relative_template,
				),
			),
		);
	};

	// phpcs:disable WordPress.Arrays.ArrayDeclarationSpacing.AssociativeArrayFound -- ACF large config arrays.

	acf_add_local_field_group(
		array(
			'key'                   => 'group_pc_page_careers',
			'title'                 => __( '採用情報ページ', $td ),
			'fields'                => array(
				array(
					'key'   => 'field_pc_careers_tab_hero',
					'label' => __( 'ヒーロー', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_careers_hero_kicker',
					'label'         => __( 'キッカー', $td ),
					'name'          => 'careers_hero_kicker',
					'type'          => 'text',
					'default_value' => 'Careers',
				),
				array(
					'key'           => 'field_pc_careers_hero_lead',
					'label'         => __( 'リード（抜粋が空のとき）', $td ),
					'name'          => 'careers_hero_lead',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '働き方を左右するトーンを先に示し、詳細ページ本文は続きへ。左右のリストは一覧性を高めるデモ構成です。',
				),
				array(
					'key'   => 'field_pc_careers_tab_intro',
					'label' => __( 'イントロ／リスト', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_careers_intro_heading',
					'label'         => __( 'イントロ見出し', $td ),
					'name'          => 'careers_intro_heading',
					'type'          => 'text',
					'default_value' => '採用のハイライト',
				),
				array(
					'key'           => 'field_pc_careers_intro_body',
					'label'         => __( 'イントロ本文', $td ),
					'name'          => 'careers_intro_body',
					'type'          => 'textarea',
					'rows'          => 4,
					'default_value' => '少数精鋭で案件に深く入り込むコースと、制作体制を支えるコースの両輪でチームが回っています。まずは下の共通前提を読みいただいたうえで、本文で募集職種の詳細を更新してください。',
				),
				array(
					'key'           => 'field_pc_careers_col_left_heading',
					'label'         => __( '左カラム見出し', $td ),
					'name'          => 'careers_col_left_heading',
					'type'          => 'text',
					'default_value' => '共通の前提（例）',
				),
				array(
					'key'           => 'field_pc_careers_col_left_item_1',
					'label'         => __( '左リスト1', $td ),
					'name'          => 'careers_col_left_item_1',
					'type'          => 'text',
					'default_value' => 'リモート＋出社のハイブリッド（チーム協議により調整）',
				),
				array(
					'key'           => 'field_pc_careers_col_left_item_2',
					'label'         => __( '左リスト2', $td ),
					'name'          => 'careers_col_left_item_2',
					'type'          => 'text',
					'default_value' => '社会・健康保険、労働環境での安全衛生教育の実施',
				),
				array(
					'key'           => 'field_pc_careers_col_left_item_3',
					'label'         => __( '左リスト3', $td ),
					'name'          => 'careers_col_left_item_3',
					'type'          => 'text',
					'default_value' => '学会・イベント参加への補助制度（デモ説明文案）',
				),
				array(
					'key'           => 'field_pc_careers_col_right_heading',
					'label'         => __( '右カラム見出し', $td ),
					'name'          => 'careers_col_right_heading',
					'type'          => 'text',
					'default_value' => '応募時のチェックリスト',
				),
				array(
					'key'           => 'field_pc_careers_col_right_item_1',
					'label'         => __( '右リスト1', $td ),
					'name'          => 'careers_col_right_item_1',
					'type'          => 'text',
					'default_value' => 'ポートフォリオもしくは直近事例の資料',
				),
				array(
					'key'           => 'field_pc_careers_col_right_item_2',
					'label'         => __( '右リスト2', $td ),
					'name'          => 'careers_col_right_item_2',
					'type'          => 'text',
					'default_value' => '勤務開始希望／選考での連絡先',
				),
				array(
					'key'           => 'field_pc_careers_col_right_item_3',
					'label'         => __( '右リスト3', $td ),
					'name'          => 'careers_col_right_item_3',
					'type'          => 'text',
					'default_value' => '自己紹介（200〜400 文字目安・プレイスホルダー）',
				),
				array(
					'key'   => 'field_pc_careers_tab_body',
					'label' => __( '本文エリア見出し', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_careers_roles_heading',
					'label'         => __( '募集・本文ブロック見出し', $td ),
					'name'          => 'careers_roles_heading',
					'type'          => 'text',
					'default_value' => '募集職種・追加情報（本文編集領域）',
				),
			),
			'location'              => $tpl_loc( 'page-templates/page-careers.php' ),
			'position'              => 'acf_after_title',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'active'                => true,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_pc_page_company',
			'title'                 => __( '会社概要ページ', $td ),
			'fields'                => array(
				array(
					'key'   => 'field_pc_company_tab_hero',
					'label' => __( 'ヒーロー', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_company_hero_kicker',
					'label'         => __( 'キッカー', $td ),
					'name'          => 'company_hero_kicker',
					'type'          => 'text',
					'default_value' => 'Company profile',
				),
				array(
					'key'           => 'field_pc_company_hero_lead',
					'label'         => __( 'リード（抜粋が空のとき）', $td ),
					'name'          => 'company_hero_lead',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '理念・沿革・概要を一覧できるコーポレート向けのレイアウトです。ヒーロー下の項目は編集画面の抜粋で差し替えられます。',
				),
				array(
					'key'   => 'field_pc_company_tab_overview',
					'label' => __( '会社概要ブロック', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_company_overview_heading',
					'label'         => __( 'ブロック見出し', $td ),
					'name'          => 'company_overview_heading',
					'type'          => 'text',
					'default_value' => '会社概要',
				),
				array(
					'key'           => 'field_pc_company_trade_name',
					'label'         => __( '商号（空ならサイトブランド名）', $td ),
					'name'          => 'company_trade_name',
					'type'          => 'text',
					'default_value' => '',
				),
				array(
					'key'           => 'field_pc_company_address',
					'label'         => __( '所在地（空ならフロントページの連絡先設定）', $td ),
					'name'          => 'company_address',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '',
				),
				array(
					'key'           => 'field_pc_company_address_fallback',
					'label'         => __( '所在地プレースホルダー（上記・フロント設定とも空のとき）', $td ),
					'name'          => 'company_address_fallback',
					'type'          => 'textarea',
					'rows'          => 2,
					'default_value' => '〒000-0000 サンプルの所在地／フロント設定の説明文と統一できます',
				),
				array(
					'key'   => 'field_pc_company_tab_message',
					'label' => __( '代表メッセージ', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_company_message_heading',
					'label'         => __( '見出し', $td ),
					'name'          => 'company_message_heading',
					'type'          => 'text',
					'default_value' => '代表メッセージ',
				),
				array(
					'key'           => 'field_pc_company_message_label',
					'label'         => __( '肩書きラベル', $td ),
					'name'          => 'company_message_label',
					'type'          => 'text',
					'default_value' => '代表取締役 ─',
				),
				array(
					'key'           => 'field_pc_company_message_body',
					'label'         => __( '本文', $td ),
					'name'          => 'company_message_body',
					'type'          => 'textarea',
					'rows'          => 4,
					'default_value' => 'デモ構成では代表挨拶のプレースホルダーを表示しています。実運用ではここを本文側のページ冒頭へ移したり、この枠のみ固定で残す運用にもできます。お客様の課題に寄り添う姿勢を一言で伝えましょう。',
				),
				array(
					'key'   => 'field_pc_company_tab_history',
					'label' => __( '沿革', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_company_history_heading',
					'label'         => __( '沿革見出し', $td ),
					'name'          => 'company_history_heading',
					'type'          => 'text',
					'default_value' => '沿革',
				),
				array(
					'key'           => 'field_pc_company_history_1_year',
					'label'         => __( '沿革1・年', $td ),
					'name'          => 'company_history_1_year',
					'type'          => 'text',
					'default_value' => '2009',
				),
				array(
					'key'           => 'field_pc_company_history_1_text',
					'label'         => __( '沿革1・説明', $td ),
					'name'          => 'company_history_1_text',
					'type'          => 'textarea',
					'rows'          => 2,
					'default_value' => '創業／地域に根ざした設計コンサルの立ち上げ',
				),
				array(
					'key'           => 'field_pc_company_history_2_year',
					'label'         => __( '沿革2・年', $td ),
					'name'          => 'company_history_2_year',
					'type'          => 'text',
					'default_value' => '2016',
				),
				array(
					'key'           => 'field_pc_company_history_2_text',
					'label'         => __( '沿革2・説明', $td ),
					'name'          => 'company_history_2_text',
					'type'          => 'textarea',
					'rows'          => 2,
					'default_value' => '業務提携の拡大・ワークショップ型サービスの整備',
				),
				array(
					'key'           => 'field_pc_company_history_3_year',
					'label'         => __( '沿革3・ラベル', $td ),
					'name'          => 'company_history_3_year',
					'type'          => 'text',
					'default_value' => '現在',
				),
				array(
					'key'           => 'field_pc_company_history_3_text',
					'label'         => __( '沿革3・説明', $td ),
					'name'          => 'company_history_3_text',
					'type'          => 'textarea',
					'rows'          => 2,
					'default_value' => '住宅・複合プロジェクト両面での設計監修を実施（例示）',
				),
			),
			'location'              => $tpl_loc( 'page-templates/page-company.php' ),
			'position'              => 'acf_after_title',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'active'                => true,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_pc_page_concept',
			'title'                 => __( 'コンセプトページ', $td ),
			'fields'                => array(
				array(
					'key'   => 'field_pc_concept_tab_hero',
					'label' => __( 'ヒーロー', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_concept_hero_kicker',
					'label'         => __( 'キッカー', $td ),
					'name'          => 'concept_hero_kicker',
					'type'          => 'text',
					'default_value' => 'Concept',
				),
				array(
					'key'           => 'field_pc_concept_hero_lead',
					'label'         => __( 'リード（抜粋が空のとき）', $td ),
					'name'          => 'concept_hero_lead',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => 'ブランドの芯となるメッセージをリードとピラーで整理する構成です。本文ブロックでは詳細ケーススタディやギャラリーを続けられます。',
				),
				array(
					'key'   => 'field_pc_concept_tab_lead',
					'label' => __( 'リード', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_concept_lead_heading',
					'label'         => __( 'リード見出し', $td ),
					'name'          => 'concept_lead_heading',
					'type'          => 'text',
					'default_value' => 'リード',
				),
				array(
					'key'           => 'field_pc_concept_lead_body',
					'label'         => __( 'リード本文', $td ),
					'name'          => 'concept_lead_body',
					'type'          => 'textarea',
					'rows'          => 4,
					'default_value' => '暮らしと土地のあいだを設計するとき、まず問うのは「誰にとっての心地よさか」。法令や効率だけでは届かない距離感まで含めて、合意に耐えるストーリーを組み立てます（デモ文言）。',
				),
				array(
					'key'   => 'field_pc_concept_tab_pillars',
					'label' => __( '三本柱', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_concept_pillars_heading',
					'label'         => __( 'ブロック見出し', $td ),
					'name'          => 'concept_pillars_heading',
					'type'          => 'text',
					'default_value' => '三本柱',
				),
				array(
					'key'           => 'field_pc_concept_pillar_1_tag',
					'label'         => __( '柱1・タグ', $td ),
					'name'          => 'concept_pillar_1_tag',
					'type'          => 'text',
					'default_value' => 'Pillar 01',
				),
				array(
					'key'           => 'field_pc_concept_pillar_1_title',
					'label'         => __( '柱1・見出し', $td ),
					'name'          => 'concept_pillar_1_title',
					'type'          => 'text',
					'default_value' => '対話からの設計',
				),
				array(
					'key'           => 'field_pc_concept_pillar_1_body',
					'label'         => __( '柱1・本文', $td ),
					'name'          => 'concept_pillar_1_body',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => 'ステークホルダーの語りを構造化し、図面に埋め込むまでの過程を透明にします（プレースホルダー）。',
				),
				array(
					'key'           => 'field_pc_concept_pillar_2_tag',
					'label'         => __( '柱2・タグ', $td ),
					'name'          => 'concept_pillar_2_tag',
					'type'          => 'text',
					'default_value' => 'Pillar 02',
				),
				array(
					'key'           => 'field_pc_concept_pillar_2_title',
					'label'         => __( '柱2・見出し', $td ),
					'name'          => 'concept_pillar_2_title',
					'type'          => 'text',
					'default_value' => '耐久と手触りの両立',
				),
				array(
					'key'           => 'field_pc_concept_pillar_2_body',
					'label'         => __( '柱2・本文', $td ),
					'name'          => 'concept_pillar_2_body',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '構造や設備の合理性と、日々の触感・光の質とのバランスを同じテーブルで検討します。',
				),
				array(
					'key'           => 'field_pc_concept_pillar_3_tag',
					'label'         => __( '柱3・タグ', $td ),
					'name'          => 'concept_pillar_3_tag',
					'type'          => 'text',
					'default_value' => 'Pillar 03',
				),
				array(
					'key'           => 'field_pc_concept_pillar_3_title',
					'label'         => __( '柱3・見出し', $td ),
					'name'          => 'concept_pillar_3_title',
					'type'          => 'text',
					'default_value' => '運用まで見据える',
				),
				array(
					'key'           => 'field_pc_concept_pillar_3_body',
					'label'         => __( '柱3・本文', $td ),
					'name'          => 'concept_pillar_3_body',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '開いてからの保守動線やリニューアル余地まで視野に入れた提案をめざします（例示）。',
				),
			),
			'location'              => $tpl_loc( 'page-templates/page-concept.php' ),
			'position'              => 'acf_after_title',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'active'                => true,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_pc_page_faq',
			'title'                 => __( 'FAQページ', $td ),
			'fields'                => array(
				array(
					'key'   => 'field_pc_faq_tab_hero',
					'label' => __( 'ヒーロー', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_faq_hero_kicker',
					'label'         => __( 'キッカー', $td ),
					'name'          => 'faq_hero_kicker',
					'type'          => 'text',
					'default_value' => 'FAQ',
				),
				array(
					'key'           => 'field_pc_faq_hero_lead',
					'label'         => __( 'リード（抜粋が空のとき）', $td ),
					'name'          => 'faq_hero_lead',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => 'キーボードでも開閉しやすいよう summary にフォーカスリングを付けています。詳細は本文ブロック側にも追記できます。',
				),
				array(
					'key'   => 'field_pc_faq_tab_list',
					'label' => __( 'Q&A', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_faq_list_heading',
					'label'         => __( 'リスト見出し', $td ),
					'name'          => 'faq_list_heading',
					'type'          => 'text',
					'default_value' => 'よくあるご質問',
				),
				array(
					'key'           => 'field_pc_faq_intro',
					'label'         => __( 'リスト前の短い説明', $td ),
					'name'          => 'faq_intro',
					'type'          => 'textarea',
					'rows'          => 2,
					'default_value' => '以下はデモ用の Q&A です。編集画面からブロックで追加した段落と併用できます。',
				),
				array(
					'key'           => 'field_pc_faq_item_1_question',
					'label'         => __( '質問1', $td ),
					'name'          => 'faq_item_1_question',
					'type'          => 'text',
					'default_value' => '初回相談から提案までどのくらいかかりますか？',
				),
				array(
					'key'           => 'field_pc_faq_item_1_answer',
					'label'         => __( '回答1', $td ),
					'name'          => 'faq_item_1_answer',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '規模により異なりますが、デモ文言としては机上検討から概略プラン提示まで 3〜6 週間を目安に記載している例です。',
				),
				array(
					'key'           => 'field_pc_faq_item_2_question',
					'label'         => __( '質問2', $td ),
					'name'          => 'faq_item_2_question',
					'type'          => 'text',
					'default_value' => '対応エリアは限定されていますか？',
				),
				array(
					'key'           => 'field_pc_faq_item_2_answer',
					'label'         => __( '回答2', $td ),
					'name'          => 'faq_item_2_answer',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '関西圏を中心にオンサイト調査を行う想定のプレースホルダーです。リモートのみの支援可否は別途ご相談、という運用にもできます。',
				),
				array(
					'key'           => 'field_pc_faq_item_3_question',
					'label'         => __( '質問3', $td ),
					'name'          => 'faq_item_3_question',
					'type'          => 'text',
					'default_value' => '見積もりやコンサル費用の支払い条件は？',
				),
				array(
					'key'           => 'field_pc_faq_item_3_answer',
					'label'         => __( '回答3', $td ),
					'name'          => 'faq_item_3_answer',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => 'フェーズごとにミールストーン請求／実費精算など、契約書ベースで記載してください（ダミー）。',
				),
				array(
					'key'           => 'field_pc_faq_item_4_question',
					'label'         => __( '質問4', $td ),
					'name'          => 'faq_item_4_question',
					'type'          => 'text',
					'default_value' => '既存建築のリノベにも対応していますか？',
				),
				array(
					'key'           => 'field_pc_faq_item_4_answer',
					'label'         => __( '回答4', $td ),
					'name'          => 'faq_item_4_answer',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '構造診断や設備更新を含む全体計画から部分改修まで幅を持たせる説明文をここに置けます。',
				),
			),
			'location'              => $tpl_loc( 'page-templates/page-faq.php' ),
			'position'              => 'acf_after_title',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'active'                => true,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_pc_page_philosophy',
			'title'                 => __( '設計理念ページ', $td ),
			'fields'                => array(
				array(
					'key'   => 'field_pc_philosophy_tab_hero',
					'label' => __( 'ヒーロー', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_philosophy_hero_kicker',
					'label'         => __( 'キッカー', $td ),
					'name'          => 'philosophy_hero_kicker',
					'type'          => 'text',
					'default_value' => 'Philosophy',
				),
				array(
					'key'           => 'field_pc_philosophy_hero_lead',
					'label'         => __( 'リード（抜粋が空のとき）', $td ),
					'name'          => 'philosophy_hero_lead',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => 'プロセスを番号付きステップで示し、タイムラインと異なる「順序」の読みやすさを狙ったレイアウトです。',
				),
				array(
					'key'   => 'field_pc_philosophy_tab_steps',
					'label' => __( 'ステップ', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_philosophy_steps_heading',
					'label'         => __( 'ステップ見出し', $td ),
					'name'          => 'philosophy_steps_heading',
					'type'          => 'text',
					'default_value' => '進め方の考え方',
				),
				array(
					'key'           => 'field_pc_philosophy_step_1_title',
					'label'         => __( 'ステップ1・見出し', $td ),
					'name'          => 'philosophy_step_1_title',
					'type'          => 'text',
					'default_value' => '現場と制度の両面調査',
				),
				array(
					'key'           => 'field_pc_philosophy_step_1_body',
					'label'         => __( 'ステップ1・本文', $td ),
					'name'          => 'philosophy_step_1_body',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '敷地の気候・動線・既存資産と、適用法規・協議要件を並列で棚卸しします（ダミー説明）。',
				),
				array(
					'key'           => 'field_pc_philosophy_step_2_title',
					'label'         => __( 'ステップ2・見出し', $td ),
					'name'          => 'philosophy_step_2_title',
					'type'          => 'text',
					'default_value' => 'シナリオの並列検討',
				),
				array(
					'key'           => 'field_pc_philosophy_step_2_body',
					'label'         => __( 'ステップ2・本文', $td ),
					'name'          => 'philosophy_step_2_body',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '単一案に縛らず、コスト・工期・将来的な拡張性を軸に複数パターンを比較します。',
				),
				array(
					'key'           => 'field_pc_philosophy_step_3_title',
					'label'         => __( 'ステップ3・見出し', $td ),
					'name'          => 'philosophy_step_3_title',
					'type'          => 'text',
					'default_value' => '合意の文書化と伴走',
				),
				array(
					'key'           => 'field_pc_philosophy_step_3_body',
					'label'         => __( 'ステップ3・本文', $td ),
					'name'          => 'philosophy_step_3_body',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '決定理由と保留事項をセットで記録し、施行・運用フェーズでも参照できる状態にします（例）。',
				),
				array(
					'key'   => 'field_pc_philosophy_tab_timeline',
					'label' => __( 'ミニタイムライン', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_philosophy_timeline_heading',
					'label'         => __( 'タイムライン見出し', $td ),
					'name'          => 'philosophy_timeline_heading',
					'type'          => 'text',
					'default_value' => 'ミニタイムライン',
				),
				array(
					'key'           => 'field_pc_philosophy_timeline_note',
					'label'         => __( 'タイムライン前の注記', $td ),
					'name'          => 'philosophy_timeline_note',
					'type'          => 'textarea',
					'rows'          => 2,
					'default_value' => '設計会社側の変遷を会社概要とは別角度でサブに載せる例です（実データに差し替えください）。',
				),
				array(
					'key'           => 'field_pc_philosophy_timeline_1_label',
					'label'         => __( 'タイムライン1・ラベル', $td ),
					'name'          => 'philosophy_timeline_1_label',
					'type'          => 'text',
					'default_value' => '試行期',
				),
				array(
					'key'           => 'field_pc_philosophy_timeline_1_desc',
					'label'         => __( 'タイムライン1・説明', $td ),
					'name'          => 'philosophy_timeline_1_desc',
					'type'          => 'textarea',
					'rows'          => 2,
					'default_value' => '地域プロジェクトでの実証とレビューのサイクル確立',
				),
				array(
					'key'           => 'field_pc_philosophy_timeline_2_label',
					'label'         => __( 'タイムライン2・ラベル', $td ),
					'name'          => 'philosophy_timeline_2_label',
					'type'          => 'text',
					'default_value' => '拡張期',
				),
				array(
					'key'           => 'field_pc_philosophy_timeline_2_desc',
					'label'         => __( 'タイムライン2・説明', $td ),
					'name'          => 'philosophy_timeline_2_desc',
					'type'          => 'textarea',
					'rows'          => 2,
					'default_value' => '複合用途・中大規模への設計監査ノウハウ蓄積（ダミー）',
				),
			),
			'location'              => $tpl_loc( 'page-templates/page-philosophy.php' ),
			'position'              => 'acf_after_title',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'active'                => true,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_pc_page_services',
			'title'                 => __( 'サービスページ', $td ),
			'fields'                => array(
				array(
					'key'   => 'field_pc_services_tab_hero',
					'label' => __( 'ヒーロー', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_services_hero_kicker',
					'label'         => __( 'キッカー', $td ),
					'name'          => 'services_hero_kicker',
					'type'          => 'text',
					'default_value' => 'Services',
				),
				array(
					'key'           => 'field_pc_services_hero_lead',
					'label'         => __( 'リード（抜粋が空のとき）', $td ),
					'name'          => 'services_hero_lead',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '主なサービス領域をカードで示す構成例です。下の説明は編集画面の本文との併せ持ちにもかかわらず、この枠のみ静的なデモにできます。',
				),
				array(
					'key'   => 'field_pc_services_tab_cards',
					'label' => __( 'カード', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_services_grid_heading',
					'label'         => __( 'グリッド見出し', $td ),
					'name'          => 'services_grid_heading',
					'type'          => 'text',
					'default_value' => 'サービス一覧',
				),
				array(
					'key'           => 'field_pc_services_card_1_title',
					'label'         => __( 'カード1・見出し', $td ),
					'name'          => 'services_card_1_title',
					'type'          => 'text',
					'default_value' => '企画／コンセプト',
				),
				array(
					'key'           => 'field_pc_services_card_1_body',
					'label'         => __( 'カード1・本文', $td ),
					'name'          => 'services_card_1_body',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '敷地や用途に応じて初期ロジックから整理し、合意ベースでの方向性宣言までをご支援します。',
				),
				array(
					'key'           => 'field_pc_services_card_2_title',
					'label'         => __( 'カード2・見出し', $td ),
					'name'          => 'services_card_2_title',
					'type'          => 'text',
					'default_value' => '基本計画〜実施設計',
				),
				array(
					'key'           => 'field_pc_services_card_2_body',
					'label'         => __( 'カード2・本文', $td ),
					'name'          => 'services_card_2_body',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '法規適合だけでなく、暮らす人の視線まで含めてプランを細かく検討します。',
				),
				array(
					'key'           => 'field_pc_services_card_3_title',
					'label'         => __( 'カード3・見出し', $td ),
					'name'          => 'services_card_3_title',
					'type'          => 'text',
					'default_value' => 'ワークショップ／伴走支援',
				),
				array(
					'key'           => 'field_pc_services_card_3_body',
					'label'         => __( 'カード3・本文', $td ),
					'name'          => 'services_card_3_body',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '関係者が同じ言葉を共有できるよう、場づくりとファシリテーションを組み込みます。',
				),
				array(
					'key'           => 'field_pc_services_card_4_title',
					'label'         => __( 'カード4・見出し', $td ),
					'name'          => 'services_card_4_title',
					'type'          => 'text',
					'default_value' => '維持管理・定期点検',
				),
				array(
					'key'           => 'field_pc_services_card_4_body',
					'label'         => __( 'カード4・本文', $td ),
					'name'          => 'services_card_4_body',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '運用フェーズにも橋渡しできる体制を一例として掲載（プレースホルダー）します。',
				),
			),
			'location'              => $tpl_loc( 'page-templates/page-services.php' ),
			'position'              => 'acf_after_title',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'active'                => true,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_pc_page_services_overview',
			'title'                 => __( 'サービス一覧（概要）ページ', $td ),
			'fields'                => array(
				array(
					'key'   => 'field_pc_sv_overview_tab_hero',
					'label' => __( 'ヒーロー', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_sv_overview_hero_kicker',
					'label'         => __( 'キッカー', $td ),
					'name'          => 'sv_overview_hero_kicker',
					'type'          => 'text',
					'default_value' => 'Services overview',
				),
				array(
					'key'           => 'field_pc_sv_overview_hero_lead',
					'label'         => __( 'リード（抜粋が空のとき）', $td ),
					'name'          => 'sv_overview_hero_lead',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '一覧性を優先したカードグリッドです。「サービス」テンプレより粒度を荒くし、 LP や資料への誘導を想定したダミー構成にしています。',
				),
				array(
					'key'   => 'field_pc_sv_overview_tab_grid',
					'label' => __( 'カードグリッド', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_sv_overview_grid_heading',
					'label'         => __( 'グリッド見出し', $td ),
					'name'          => 'sv_overview_grid_heading',
					'type'          => 'text',
					'default_value' => 'サービスカード（静的ダミー）',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_1_kicker',
					'label'         => __( 'カード1・キッカー', $td ),
					'name'          => 'sv_overview_card_1_kicker',
					'type'          => 'text',
					'default_value' => 'Consult',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_1_title',
					'label'         => __( 'カード1・見出し', $td ),
					'name'          => 'sv_overview_card_1_title',
					'type'          => 'text',
					'default_value' => '計画コンサルティング',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_1_text',
					'label'         => __( 'カード1・本文', $td ),
					'name'          => 'sv_overview_card_1_text',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => 'プロジェクト初期の論点整理、ステークホルダー調整、スケジュールラインのたたき台をご用意します（デモ）。',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_1_meta',
					'label'         => __( 'カード1・メタ行', $td ),
					'name'          => 'sv_overview_card_1_meta',
					'type'          => 'text',
					'default_value' => '期間の目安：2〜8 週',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_2_kicker',
					'label'         => __( 'カード2・キッカー', $td ),
					'name'          => 'sv_overview_card_2_kicker',
					'type'          => 'text',
					'default_value' => 'Design',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_2_title',
					'label'         => __( 'カード2・見出し', $td ),
					'name'          => 'sv_overview_card_2_title',
					'type'          => 'text',
					'default_value' => '設計・監理',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_2_text',
					'label'         => __( 'カード2・本文', $td ),
					'name'          => 'sv_overview_card_2_text',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '基本〜実施設計、工事監理までの一連業務をワンストップで記載する例です。実際の許認可関与範囲は脚注で補足できます。',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_2_meta',
					'label'         => __( 'カード2・メタ行', $td ),
					'name'          => 'sv_overview_card_2_meta',
					'type'          => 'text',
					'default_value' => '対応：新築／増改築（例）',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_3_kicker',
					'label'         => __( 'カード3・キッカー', $td ),
					'name'          => 'sv_overview_card_3_kicker',
					'type'          => 'text',
					'default_value' => 'Workshop',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_3_title',
					'label'         => __( 'カード3・見出し', $td ),
					'name'          => 'sv_overview_card_3_title',
					'type'          => 'text',
					'default_value' => '参加型ワークショップ',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_3_text',
					'label'         => __( 'カード3・本文', $td ),
					'name'          => 'sv_overview_card_3_text',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '模型や写真を用いた短時間セッションで、方向性の早期共有を狙うサービスカードのダミー文言です。',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_3_meta',
					'label'         => __( 'カード3・メタ行', $td ),
					'name'          => 'sv_overview_card_3_meta',
					'type'          => 'text',
					'default_value' => '開催形式：オンサイト／オンライン',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_4_kicker',
					'label'         => __( 'カード4・キッカー', $td ),
					'name'          => 'sv_overview_card_4_kicker',
					'type'          => 'text',
					'default_value' => 'Aftercare',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_4_title',
					'label'         => __( 'カード4・見出し', $td ),
					'name'          => 'sv_overview_card_4_title',
					'type'          => 'text',
					'default_value' => '竣工後フォロー',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_4_text',
					'label'         => __( 'カード4・本文', $td ),
					'name'          => 'sv_overview_card_4_text',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '定期点検プランや簡易リニューアル相談など、運用フェーズに寄り添う行を別カードとして提示できます。',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_4_meta',
					'label'         => __( 'カード4・メタ行', $td ),
					'name'          => 'sv_overview_card_4_meta',
					'type'          => 'text',
					'default_value' => '契約プラン別（ダミー）',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_5_kicker',
					'label'         => __( 'カード5・キッカー', $td ),
					'name'          => 'sv_overview_card_5_kicker',
					'type'          => 'text',
					'default_value' => 'Partners',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_5_title',
					'label'         => __( 'カード5・見出し', $td ),
					'name'          => 'sv_overview_card_5_title',
					'type'          => 'text',
					'default_value' => '協働ネットワーク',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_5_text',
					'label'         => __( 'カード5・本文', $td ),
					'name'          => 'sv_overview_card_5_text',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '構造・設備・植栽など、パートナー事務所との連携体制を一覧で見せるカードのサンプルです。',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_5_meta',
					'label'         => __( 'カード5・メタ行', $td ),
					'name'          => 'sv_overview_card_5_meta',
					'type'          => 'text',
					'default_value' => 'ご紹介は個別にお問い合わせ',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_6_kicker',
					'label'         => __( 'カード6・キッカー', $td ),
					'name'          => 'sv_overview_card_6_kicker',
					'type'          => 'text',
					'default_value' => 'Contact',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_6_title',
					'label'         => __( 'カード6・見出し', $td ),
					'name'          => 'sv_overview_card_6_title',
					'type'          => 'text',
					'default_value' => 'お問い合わせ・資料請求',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_6_text',
					'label'         => __( 'カード6・本文', $td ),
					'name'          => 'sv_overview_card_6_text',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '詳細ページへ誘導するクロージング用カードとしても利用できます。リンクはメニューやボタンブロックで後から追加してください。',
				),
				array(
					'key'           => 'field_pc_sv_overview_card_6_meta',
					'label'         => __( 'カード6・メタ行', $td ),
					'name'          => 'sv_overview_card_6_meta',
					'type'          => 'text',
					'default_value' => 'メール／電話／フォーム',
				),
			),
			'location'              => $tpl_loc( 'page-templates/page-services-overview.php' ),
			'position'              => 'acf_after_title',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'active'                => true,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_pc_page_privacy',
			'title'                 => __( 'プライバシーポリシーページ', $td ),
			'fields'                => array(
				array(
					'key'   => 'field_pc_privacy_tab_hero',
					'label' => __( 'ヒーロー', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_privacy_hero_kicker',
					'label'         => __( 'キッカー', $td ),
					'name'          => 'privacy_hero_kicker',
					'type'          => 'text',
					'default_value' => 'Privacy policy',
				),
				array(
					'key'           => 'field_pc_privacy_hero_lead',
					'label'         => __( 'リード（抜粋が空のとき）', $td ),
					'name'          => 'privacy_hero_lead',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '左（広い画面ではサイド）のナビから章へジャンプできます。エディタ側で追加した見出しとは別に、この枠は静的ガイドとして残せます。',
				),
				array(
					'key'   => 'field_pc_privacy_tab_sections',
					'label' => __( '章立て', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_privacy_body_heading',
					'label'         => __( '本文エリア見出し', $td ),
					'name'          => 'privacy_body_heading',
					'type'          => 'text',
					'default_value' => '規約本文',
				),
				array(
					'key'           => 'field_pc_privacy_toc_title',
					'label'         => __( '目次タイトル', $td ),
					'name'          => 'privacy_toc_title',
					'type'          => 'text',
					'default_value' => '目次',
				),
				array(
					'key'           => 'field_pc_privacy_section_1_id',
					'label'         => __( '章1・アンカーID', $td ),
					'name'          => 'privacy_section_1_id',
					'type'          => 'text',
					'default_value' => 'privacy-about',
				),
				array(
					'key'           => 'field_pc_privacy_section_1_title',
					'label'         => __( '章1・見出し', $td ),
					'name'          => 'privacy_section_1_title',
					'type'          => 'text',
					'default_value' => 'はじめに',
				),
				array(
					'key'           => 'field_pc_privacy_section_1_text',
					'label'         => __( '章1・本文', $td ),
					'name'          => 'privacy_section_1_text',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '本ページは個人情報の取り扱いについて告知するためのレイアウトデモです。実運用では法令および貴社ポリシーに沿って全文を差し替えてください。',
				),
				array(
					'key'           => 'field_pc_privacy_section_2_id',
					'label'         => __( '章2・アンカーID', $td ),
					'name'          => 'privacy_section_2_id',
					'type'          => 'text',
					'default_value' => 'privacy-scope',
				),
				array(
					'key'           => 'field_pc_privacy_section_2_title',
					'label'         => __( '章2・見出し', $td ),
					'name'          => 'privacy_section_2_title',
					'type'          => 'text',
					'default_value' => '適用範囲',
				),
				array(
					'key'           => 'field_pc_privacy_section_2_text',
					'label'         => __( '章2・本文', $td ),
					'name'          => 'privacy_section_2_text',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => 'ウェブサイト経由で取得する情報、対面・電話・メールで取得する情報など、収集チャネルごとに適用範囲を定義します（プレースホルダー）。',
				),
				array(
					'key'           => 'field_pc_privacy_section_3_id',
					'label'         => __( '章3・アンカーID', $td ),
					'name'          => 'privacy_section_3_id',
					'type'          => 'text',
					'default_value' => 'privacy-purpose',
				),
				array(
					'key'           => 'field_pc_privacy_section_3_title',
					'label'         => __( '章3・見出し', $td ),
					'name'          => 'privacy_section_3_title',
					'type'          => 'text',
					'default_value' => '利用目的',
				),
				array(
					'key'           => 'field_pc_privacy_section_3_text',
					'label'         => __( '章3・本文', $td ),
					'name'          => 'privacy_section_3_text',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '問い合わせ対応、資料送付、サービス向上のための分析など、目的別に列挙します。第三者提供の有無もこの付近で明示します（ダミー）。',
				),
				array(
					'key'           => 'field_pc_privacy_section_4_id',
					'label'         => __( '章4・アンカーID', $td ),
					'name'          => 'privacy_section_4_id',
					'type'          => 'text',
					'default_value' => 'privacy-retention',
				),
				array(
					'key'           => 'field_pc_privacy_section_4_title',
					'label'         => __( '章4・見出し', $td ),
					'name'          => 'privacy_section_4_title',
					'type'          => 'text',
					'default_value' => '保管期間と安全管理',
				),
				array(
					'key'           => 'field_pc_privacy_section_4_text',
					'label'         => __( '章4・本文', $td ),
					'name'          => 'privacy_section_4_text',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '法令で定める保存期間、アクセス権限、委託先の監督などを段落で説明するブロックの見本文言です。',
				),
				array(
					'key'           => 'field_pc_privacy_section_5_id',
					'label'         => __( '章5・アンカーID', $td ),
					'name'          => 'privacy_section_5_id',
					'type'          => 'text',
					'default_value' => 'privacy-rights',
				),
				array(
					'key'           => 'field_pc_privacy_section_5_title',
					'label'         => __( '章5・見出し', $td ),
					'name'          => 'privacy_section_5_title',
					'type'          => 'text',
					'default_value' => '開示・訂正・削除の請求',
				),
				array(
					'key'           => 'field_pc_privacy_section_5_text',
					'label'         => __( '章5・本文', $td ),
					'name'          => 'privacy_section_5_text',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '手続き方法、応答目安、認証に必要な情報などを記載するセクションのスターターテキストです。',
				),
				array(
					'key'           => 'field_pc_privacy_section_6_id',
					'label'         => __( '章6・アンカーID', $td ),
					'name'          => 'privacy_section_6_id',
					'type'          => 'text',
					'default_value' => 'privacy-contact',
				),
				array(
					'key'           => 'field_pc_privacy_section_6_title',
					'label'         => __( '章6・見出し', $td ),
					'name'          => 'privacy_section_6_title',
					'type'          => 'text',
					'default_value' => 'お問い合わせ窓口',
				),
				array(
					'key'           => 'field_pc_privacy_section_6_text',
					'label'         => __( '章6・本文', $td ),
					'name'          => 'privacy_section_6_text',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => '個人情報保護管理者／連絡先メール・電話などを記載します。会社概要ページと表記を揃えると運用が楽になります（例）。',
				),
				array(
					'key'           => 'field_pc_privacy_editor_heading',
					'label'         => __( 'エディタブロック見出し', $td ),
					'name'          => 'privacy_editor_heading',
					'type'          => 'text',
					'default_value' => 'エディタからの追加ブロック',
				),
			),
			'location'              => $tpl_loc( 'page-templates/page-privacy-layout.php' ),
			'position'              => 'acf_after_title',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'active'                => true,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_pc_page_contact',
			'title'                 => __( 'お問い合わせページ', $td ),
			'fields'                => array(
				array(
					'key'   => 'field_pc_contact_tab_hero',
					'label' => __( 'ヒーロー', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_contact_hero_kicker',
					'label'         => __( 'キッカー', $td ),
					'name'          => 'contact_hero_kicker',
					'type'          => 'text',
					'default_value' => 'Contact',
				),
				array(
					'key'           => 'field_pc_contact_hero_lead',
					'label'         => __( 'リード（抜粋が空のとき）', $td ),
					'name'          => 'contact_hero_lead',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => 'ご質問・ご相談は電話またはメールにてご連絡ください。入力フォームをお使いの際は、この下のご案内に沿って本文ブロックまたはショートコードをご利用いただけます。',
				),
				array(
					'key'   => 'field_pc_contact_tab_channels',
					'label' => __( 'チャネル', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_contact_summary',
					'label'         => __( '冒頭サマリー', $td ),
					'name'          => 'contact_summary',
					'type'          => 'textarea',
					'rows'          => 2,
					'default_value' => '内容を確認のうえ担当より折り返しご連絡します。自動音声のみの時間帯を除き、日中は担当が対応する想定です。',
				),
				array(
					'key'           => 'field_pc_contact_phone_heading',
					'label'         => __( '電話ブロック見出し', $td ),
					'name'          => 'contact_phone_heading',
					'type'          => 'text',
					'default_value' => 'お電話',
				),
				array(
					'key'           => 'field_pc_contact_phone_note',
					'label'         => __( '電話ブロック注釈', $td ),
					'name'          => 'contact_phone_note',
					'type'          => 'textarea',
					'rows'          => 2,
					'default_value' => '平日のご案内時間帯のみ担当が対応いたします（例示文言）。',
				),
				array(
					'key'           => 'field_pc_contact_mail_heading',
					'label'         => __( 'メールブロック見出し', $td ),
					'name'          => 'contact_mail_heading',
					'type'          => 'text',
					'default_value' => 'メール',
				),
				array(
					'key'           => 'field_pc_contact_mail_note',
					'label'         => __( 'メールブロック注釈', $td ),
					'name'          => 'contact_mail_note',
					'type'          => 'textarea',
					'rows'          => 2,
					'default_value' => '折り返しまでに時間を要する場合があります。',
				),
				array(
					'key'           => 'field_pc_contact_form_heading',
					'label'         => __( 'フォームブロック見出し', $td ),
					'name'          => 'contact_form_heading',
					'type'          => 'text',
					'default_value' => 'フォームでのお問い合わせ',
				),
				array(
					'key'           => 'field_pc_contact_form_note',
					'label'         => __( 'フォームブロック注釈', $td ),
					'name'          => 'contact_form_note',
					'type'          => 'textarea',
					'rows'          => 2,
					'default_value' => 'Contact Form 7 などのプラグインを導入する場合、この下のページ本文にショートコードやフォームブロックを追加してください。',
				),
				array(
					'key'   => 'field_pc_contact_tab_bottom',
					'label' => __( '本文エリア', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				array(
					'key'           => 'field_pc_contact_bottom_heading',
					'label'         => __( '本文エリア見出し', $td ),
					'name'          => 'contact_bottom_heading',
					'type'          => 'text',
					'default_value' => '本文・詳細でのご案内',
				),
			),
			'location'              => $tpl_loc( 'page-templates/page-contact.php' ),
			'position'              => 'acf_after_title',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'active'                => true,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_pc_page_contact_structured',
			'title'                 => __( 'お問い合わせ（構造化レイアウト）', $td ),
			'fields'                => array(
				array(
					'key'           => 'field_pc_contact_struct_phone_heading',
					'label'         => __( '電話ブロック見出し', $td ),
					'name'          => 'contact_struct_phone_heading',
					'type'          => 'text',
					'default_value' => 'お電話',
				),
				array(
					'key'           => 'field_pc_contact_struct_phone_hint',
					'label'         => __( '電話ブロック補足', $td ),
					'name'          => 'contact_struct_phone_hint',
					'type'          => 'textarea',
					'rows'          => 2,
					'default_value' => '自動音声のみの時間帯を除き、日中に担当が対応します。',
				),
				array(
					'key'           => 'field_pc_contact_struct_mail_heading',
					'label'         => __( 'メール／フォーム案内見出し', $td ),
					'name'          => 'contact_struct_mail_heading',
					'type'          => 'text',
					'default_value' => 'メールフォームについて',
				),
				array(
					'key'           => 'field_pc_contact_struct_mail_body',
					'label'         => __( 'メール／フォーム案内本文', $td ),
					'name'          => 'contact_struct_mail_body',
					'type'          => 'textarea',
					'rows'          => 3,
					'default_value' => 'Contact Form 7 などのプラグインを導入する場合、このブロック直下にショートコードやブロックを追加してください（デモ環境では未接続です）。',
				),
				array(
					'key'           => 'field_pc_contact_struct_address_heading',
					'label'         => __( '所在地ブロック見出し', $td ),
					'name'          => 'contact_struct_address_heading',
					'type'          => 'text',
					'default_value' => '所在地・受付時間',
				),
				array(
					'key'           => 'field_pc_contact_struct_address_body',
					'label'         => __( '所在地・受付（空ならフロント連絡先設定）', $td ),
					'name'          => 'contact_struct_address_body',
					'type'          => 'textarea',
					'rows'          => 4,
					'default_value' => '',
				),
			),
			'location'              => $tpl_loc( 'page-templates/template-contact-page.php' ),
			'position'              => 'acf_after_title',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'active'                => true,
		)
	);

	$quests_text_field = static function ( string $key, string $label, string $name, string $default_value, int $rows = 2 ): array {
		return array(
			'key'           => $key,
			'label'         => __( $label, THEME_GETTEXT_DOMAIN ),
			'name'          => $name,
			'type'          => $rows > 1 ? 'textarea' : 'text',
			'rows'          => $rows,
			'instructions'  => __( 'Quests 専用ページ内の同名ブロックに表示されます。フロントページには反映されません。', THEME_GETTEXT_DOMAIN ),
			'default_value' => $default_value,
		);
	};

	acf_add_local_field_group(
		array(
			'key'                   => 'group_pc_page_quests',
			'title'                 => __( 'Quests ページ', $td ),
			'fields'                => array(
				array(
					'key'   => 'field_pc_quests_tab_main',
					'label' => __( 'メイン', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				$quests_text_field( 'field_pc_quests_hero_title', 'ヒーロー見出し', 'quests_hero_title', "Samplexx\nLayout Text Dummyxx", 3 ),
				$quests_text_field( 'field_pc_quests_about_copy', 'About 上部コピー', 'quests_about_copy', "Samplexx\nLayout Textxxxx", 3 ),
				$quests_text_field( 'field_pc_quests_about_heading', 'About 見出し', 'quests_about_heading', '文字と「暮らす」', 1 ),
				$quests_text_field( 'field_pc_quests_about_body', 'About 本文', 'quests_about_body', "ここには日本語の仮文章を配置しています。\n文字量と改行の見え方を保つため、同じ程度の長さで構成したダミーテキストです。\n実際の説明内容ではなく、画面上の余白や行間を確認するために、\n日本語のまま置き換えています。\n本文の密度が大きく変わらないよう、文の長さと折り返しを調整しています。\n「仮の文字列をここに入れています」\n「表示確認のための文章です」\n「元の内容を残さず、見た目だけを合わせています」\nSample Textは説明本文ではありません。\nレイアウト確認用の仮文として、全体の分量を元の構成に近づけています。", 8 ),
				array(
					'key'   => 'field_pc_quests_tab_sections',
					'label' => __( '本文セクション', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				$quests_text_field( 'field_pc_quests_intro_kicker', 'Introduction ラベル', 'quests_intro_kicker', 'Introduction', 1 ),
				$quests_text_field( 'field_pc_quests_intro_heading', 'Introduction 見出し', 'quests_intro_heading', 'Hello! This is Sample Text.', 1 ),
				$quests_text_field( 'field_pc_quests_intro_body', 'Introduction 本文', 'quests_intro_body', 'ここには、文字数の確認に使うための仮の文章を配置しています。意味を持たない説明文として、見た目の長さや行数が大きく変わらないように調整しています。読み物としての内容ではなく、余白や折り返し、段落の密度を確認するための日本語ダミーテキストです。表示位置や雰囲気を保つため、同じ程度の長さで構成しています。', 4 ),
				$quests_text_field( 'field_pc_quests_feature_u', 'Quests 強調ラベル', 'quests_feature_u', "Samplex\nTextxx", 2 ),
				$quests_text_field( 'field_pc_quests_feature_heading', 'Quests 見出し', 'quests_feature_heading', 'Samplex-only', 1 ),
				$quests_text_field( 'field_pc_quests_feature_body', 'Quests 本文', 'quests_feature_body', "「サンプル\nテキスト」は表示確認のために配置した仮の文章です。日本語の長さや改行の入り方を保ちながら、意味のあるサービス説明にならないよう調整しています。画面上の余白、文字量、読みやすさを確認するためのダミーテキストとして、同じ程度の密度で構成しています。", 4 ),
				array(
					'key'   => 'field_pc_quests_tab_cards',
					'label' => __( '下部カード', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				$quests_text_field( 'field_pc_quests_education_kicker', 'Education 大見出しラベル', 'quests_education_kicker', 'Surround yourself with English！', 1 ),
				$quests_text_field( 'field_pc_quests_education_heading', 'Education 大見出し', 'quests_education_heading', '日々の文字に文字を', 1 ),
				$quests_text_field( 'field_pc_quests_education_card_kicker', 'Education カードラベル', 'quests_education_card_kicker', 'Education', 1 ),
				$quests_text_field( 'field_pc_quests_education_card_heading', 'Education カード見出し', 'quests_education_card_heading', '文字文字', 1 ),
				$quests_text_field( 'field_pc_quests_education_card_body', 'Education カード本文', 'quests_education_card_body', '仮の日本語テキストをここに配置しています。本文の量や折り返しを確認するための文章で、実際の説明として読ませる内容ではありません。表示の密度を保つため、同じくらいの長さで構成しています。', 4 ),
				$quests_text_field( 'field_pc_quests_life_1_kicker', 'LIFE 1 ラベル', 'quests_life_1_kicker', 'LIFE', 1 ),
				$quests_text_field( 'field_pc_quests_life_1_heading', 'LIFE 1 見出し', 'quests_life_1_heading', '文字のある文字', 1 ),
				$quests_text_field( 'field_pc_quests_life_1_body', 'LIFE 1 本文', 'quests_life_1_body', "Sample\ntext remains here for layout checking only. The sentence length is adjusted to keep the visual rhythm close to the original while avoiding real descriptive content. Japanese text is replaced separately so the mixed language balance stays similar.", 4 ),
				$quests_text_field( 'field_pc_quests_life_2_kicker', 'LIFE 2 ラベル', 'quests_life_2_kicker', 'LIFE', 1 ),
				$quests_text_field( 'field_pc_quests_life_2_heading', 'LIFE 2 見出し', 'quests_life_2_heading', '文字のある文字', 1 ),
				$quests_text_field( 'field_pc_quests_life_2_body', 'LIFE 2 本文', 'quests_life_2_body', "Sample\ntext remains here for layout checking only. The sentence length is adjusted to keep the visual rhythm close to the original while avoiding real descriptive content. Japanese text is replaced separately so the mixed language balance stays similar.", 4 ),
				$quests_text_field( 'field_pc_quests_enjoy_kicker', 'Enjoy ラベル', 'quests_enjoy_kicker', 'Enjoy', 1 ),
				$quests_text_field( 'field_pc_quests_enjoy_heading', 'Enjoy 見出し', 'quests_enjoy_heading', '文字で遊ぶ', 1 ),
				$quests_text_field( 'field_pc_quests_enjoy_body', 'Enjoy 本文', 'quests_enjoy_body', "Sample\ntext is placed here as a neutral placeholder. It keeps a similar amount of visible content while removing the original message. The wording is intentionally generic so only the layout and balance can be checked.", 4 ),
				$quests_text_field( 'field_pc_quests_closing_big', '下部大きいコピー', 'quests_closing_big', "Sample text for layout\nbalance in this area\nthat keeps the original\nline volume", 4 ),
				$quests_text_field( 'field_pc_quests_closing_small', '下部小さいコピー（HTML可）', 'quests_closing_small', 'ここにも仮の文字列を<span>同じ量だけ置きます。</span>', 2 ),
			),
			'location'              => $tpl_loc( 'page-templates/page-quests.php' ),
			'position'              => 'acf_after_title',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'active'                => true,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_pc_page_quests_service',
			'title'                 => __( 'Quests サービスページ', $td ),
			'fields'                => array(
				array(
					'key'   => 'field_pc_quests_service_tab_main',
					'label' => __( 'メイン', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				$quests_text_field( 'field_pc_quests_service_hero_label', 'ヒーロー英字', 'quests_service_hero_label', 'Service', 1 ),
				$quests_text_field( 'field_pc_quests_service_hero_small', 'ヒーロー小見出し', 'quests_service_hero_small', '文字文字紹介', 1 ),
				$quests_text_field( 'field_pc_quests_service_about_copy', 'About 上部コピー', 'quests_service_about_copy', "Let's speak English \nand immerse ourselves\nin the world of English", 3 ),
				$quests_text_field( 'field_pc_quests_service_about_heading', 'About 見出し', 'quests_service_about_heading', '文字と「暮らす」', 1 ),
				$quests_text_field( 'field_pc_quests_service_about_body', 'About 本文', 'quests_service_about_body', "これは表示確認用の仮文章です。\n文字数と改行の流れを保つために配置した日本語の文章で、\n実際の説明内容として読むことは想定していません。\n余白、行間、段落の見え方を確認するため、\n近い長さの文を並べています。\n画面内での密度が大きく変わらないよう、\n日本語のままダミーの内容に差し替えています。\nここでは意味よりもレイアウト確認を優先します。\n「仮の文章をここに配置しています」\n「同じ程度の長さになるよう調整しています」\n「本文の見た目だけを確認するための文字列です」\nSample Textは説明本文ではありません。\n表示確認のための仮の文言を配置し、全体の分量を\n元の構成に近づけています。", 8 ),
				array(
					'key'   => 'field_pc_quests_service_tab_points',
					'label' => __( '説明・ポイント', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				$quests_text_field( 'field_pc_quests_service_intro_kicker', '説明ラベル', 'quests_service_intro_kicker', 'Samplex Textxx', 1 ),
				$quests_text_field( 'field_pc_quests_service_intro_heading', '説明見出し', 'quests_service_intro_heading', 'とは', 1 ),
				$quests_text_field( 'field_pc_quests_service_intro_body', '説明本文', 'quests_service_intro_body', "「サンプル\nテキスト」は表示確認用の仮文章です。文章量と改行位置が大きく変わらないように調整し、内容としての意味を持たせず、見た目のバランスだけを確認できるようにしています。", 3 ),
				$quests_text_field( 'field_pc_quests_service_point_1_kicker', 'Point 1 ラベル', 'quests_service_point_1_kicker', 'point 1', 1 ),
				$quests_text_field( 'field_pc_quests_service_point_1_heading', 'Point 1 見出し', 'quests_service_point_1_heading', '文字しか話さない環境', 1 ),
				$quests_text_field( 'field_pc_quests_service_point_1_body', 'Point 1 本文', 'quests_service_point_1_body', 'ここには日本語のダミーテキストを配置しています。文章の長さ、行の折り返し、見出し下の余白を確認するための内容です。実際のサービス説明ではなく、画面上の密度を保つために、同程度の分量で構成しています。必要以上に意味を持たせず、読み物ではない仮文として扱えるようにしています。', 4 ),
				$quests_text_field( 'field_pc_quests_service_point_2_kicker', 'Point 2 ラベル', 'quests_service_point_2_kicker', 'point 2', 1 ),
				$quests_text_field( 'field_pc_quests_service_point_2_heading', 'Point 2 見出し', 'quests_service_point_2_heading', '文字文字以外の充実したカリキュラム', 1 ),
				$quests_text_field( 'field_pc_quests_service_point_2_body', 'Point 2 本文', 'quests_service_point_2_body', "Sample\ntext is used here only to keep the visual length close to the original. The surrounding Japanese portion is also generic placeholder wording, so this block can be checked without leaving the original message in place.", 4 ),
				$quests_text_field( 'field_pc_quests_service_long_u', '長文ブロック強調ラベル', 'quests_service_long_u', "Samplex\nTextxx", 2 ),
				$quests_text_field( 'field_pc_quests_service_long_heading', '長文ブロック見出し', 'quests_service_long_heading', 'アイウエオカキクケコとは？', 1 ),
				$quests_text_field( 'field_pc_quests_service_long_body', '長文ブロック本文', 'quests_service_long_body', "ここには日本語の仮文章を配置し、行の高さと余白を確認します。\n\n対象や内容を示す実文ではなく、文字量を保つための文章です。\n\n段落の見え方が大きく変わらないよう、同程度の長さで調整しています。\n\n（仮として）\n・日本語の仮文を通じて表示の密度を確認\n・見た目の分量を保つためのサンプルテキスト！\n・意味を持たない文章を並べて、折り返しを確認します！\n\nここに続く文章もダミーです。元の説明文が残らないようにしながら、表示のまとまりが崩れない程度の文字量で構成しています。\n最後の行も確認用の日本語テキストとして配置しています", 8 ),
				array(
					'key'   => 'field_pc_quests_service_tab_plan',
					'label' => __( '料金・エリア・フロー', $td ),
					'name'  => '',
					'type'  => 'tab',
				),
				$quests_text_field( 'field_pc_quests_service_plan_heading', 'PLAN 見出し', 'quests_service_plan_heading', 'PLAN', 1 ),
				$quests_text_field( 'field_pc_quests_service_plan_time', '時間表記', 'quests_service_plan_time', '文字時間7：00～22：00', 1 ),
				$quests_text_field( 'field_pc_quests_service_price_heading', '料金表見出し', 'quests_service_price_heading', '文字一覧', 1 ),
				$quests_text_field( 'field_pc_quests_service_price_table', '料金表 HTML', 'quests_service_price_table', '<table><tr><td><div><span style="font-size:0.9em;">１チケット（7:00〜22:00） / １文字</span></div></td><td><div>0,000円</div></td></tr><tr><td><div>１Txt（9文字）</div></td><td><div><span style="font-size:0.9em;">00,000円</span></div></td></tr><tr><td><div>文字同行（文字費・文字・文字費別）</div></td><td><div>文字列</div></td></tr></table>', 6 ),
				$quests_text_field( 'field_pc_quests_service_price_note', '料金注記', 'quests_service_price_note', '※表示文字は税込です', 1 ),
				$quests_text_field( 'field_pc_quests_service_area_heading', '対応エリア見出し', 'quests_service_area_heading', '対応文字列', 1 ),
				$quests_text_field( 'field_pc_quests_service_area_table', '対応エリア表 HTML', 'quests_service_area_table', '<table><tr><td><div>文字都</div></td><td><div>文字</div></td></tr><tr><td><div>文字文字</div></td><td><div>文字</div></td></tr><tr><td><div>文字県</div></td><td><div>文字</div></td></tr><tr><td><div>文字県</div></td><td><div>文字</div></td></tr></table>', 6 ),
				$quests_text_field( 'field_pc_quests_service_flow_kicker', 'Flow ラベル', 'quests_service_flow_kicker', 'Flow', 1 ),
				$quests_text_field( 'field_pc_quests_service_flow_heading', 'Flow 見出し', 'quests_service_flow_heading', '文字までの流れ', 1 ),
				$quests_text_field( 'field_pc_quests_service_flow_1', 'Flow 1', 'quests_service_flow_1', '文字文字文字30分', 1 ),
				$quests_text_field( 'field_pc_quests_service_flow_2', 'Flow 2', 'quests_service_flow_2', 'テキストのご購入', 1 ),
				$quests_text_field( 'field_pc_quests_service_flow_3', 'Flow 3', 'quests_service_flow_3', '次回ご文字の日程を選択', 1 ),
				$quests_text_field( 'field_pc_quests_service_flow_4_heading', 'Flow 4 見出し', 'quests_service_flow_4_heading', 'テキストの選択', 1 ),
				$quests_text_field( 'field_pc_quests_service_flow_4_body', 'Flow 4 本文', 'quests_service_flow_4_body', "テキスト何枚（何時間）、もしくは１TXT（９文字）かを選択\n※１日８文字までもしくは１Txtが選択できます", 3 ),
				$quests_text_field( 'field_pc_quests_service_flow_5', 'Flow 5', 'quests_service_flow_5', 'ご文字を希望のテキストを選択する', 1 ),
				$quests_text_field( 'field_pc_quests_service_flow_6_heading', 'Flow 6 見出し', 'quests_service_flow_6_heading', 'ご文字完了', 1 ),
				$quests_text_field( 'field_pc_quests_service_flow_6_body', 'Flow 6 本文', 'quests_service_flow_6_body', '※文字・テキストは４８時間前まで', 2 ),
				$quests_text_field( 'field_pc_quests_service_cta_heading', 'CTA 見出し', 'quests_service_cta_heading', "Let's sample layout\ntogether!", 2 ),
				$quests_text_field( 'field_pc_quests_service_cta_label', 'CTA ラベル', 'quests_service_cta_label', 'Contact', 1 ),
			),
			'location'              => $tpl_loc( 'page-templates/page-quests-service.php' ),
			'position'              => 'acf_after_title',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'active'                => true,
		)
	);

	// phpcs:enable WordPress.Arrays.ArrayDeclarationSpacing.AssociativeArrayFound
}
add_action( 'acf/init', 'theme_register_acf_page_template_groups' );
